gamin:change the SOURCE URL
lunar-linux/moonbase-other pull request #1886
Opened 2022-08-10 06:07 UTC by lhw828

2022-08-10 06:11 UTC, lunar-linux-b01 commented
SUCCESS!

2022-08-11 21:00 UTC, Ratler requested changes

2022-08-11 21:00 UTC, Ratler commented on utils/gamin/DETAILS
> +      SOURCE_URL=https://mirrors.ustc.edu.cn/gnome/sources/gamin/0.1/
We need to find a better mirror than from China.

2022-08-12 00:56 UTC, lunar-linux-b01 commented
SUCCESS!

2022-10-23 22:27 UTC, stumbles commented
We don't accept a China link.

Use this;

https://salsa.debian.org/gnome-team/gamin/-/archive/upstream/0.1.10/gamin-upstream-0.1.10.tar.bz2

2022-12-23 13:54 UTC, stumbles commented
All patches apply fine here so don't know why CI would bork on them.

2022-12-23 13:54 UTC, merged