fuse:bump to 3.11.0
lunar-linux/moonbase-other pull request #1888
Opened 2022-08-10 07:38 UTC by lhw828

2022-08-10 08:16 UTC, lunar-linux-b01 commented
SUCCESS!

2022-08-11 20:56 UTC, Ratler requested changes

2022-08-11 20:56 UTC, Ratler commented on filesys/fuse/BUILD
>  if module_installed systemd; then
We can drop the if check for systems, since that would always be present.

That init file should always be removed :)

2022-08-12 01:01 UTC, lunar-linux-b01 commented
SUCCESS!

2022-08-21 20:00 UTC, stumbles commented
There are two fuse modules in other. Fuse and fuse-3 (currently 3.11.x). They are not the same. Last I tried a while back locally, using fuse at version 3.11.x caused some dependent modules not to work. Its been a while since testing this, so before bumping please thoroughly check dependent modules will still work.

2022-08-22 03:03 UTC, closed without merging